### PR TITLE
Lua enhancements

### PR DESCRIPTION
**Pull request by SineSwiper**
This adds a bunch of new functionality and fixes to the Lua engine.  These include:

* New functions: `rom.getfilename`, `movie.play`, `movie.record`
* Enhancements to existing functions: `getemuscreen` in `gui.gdscreenshot`, `base64` in `rom.gethash`
* Documentation for all of the above
* LuaJIT support when `SYSTEM_LUA` is set
* Stack traces for Lua errors
* Removal of extra newlines for Lua print in Linux

### CODE REVIEW

**Comment by bbbradsmith** [comment]
Haven't tested the new functions, but the code change looks okay after a short review, it compiles, and a few lua scripts I tested seem to still work correctly. This looks good to me.

**Comment by Flux3on** [comment]
MERGE BASTION

**Comment by zeromus** [comment]
Are you going to be making more commits along these same lines

**Comment by zeromus** [comment]
:zap:  SHAZAM! :zap:  You're now a committer. Do whatever you want to lua. If you want to do something else or something crazier, find us on irc

**Comment by SineSwiper** [comment]
Thanks!

Any objection to this branch in particular, and if not, would you be able to merge this?  I think I have a commit bit, but not GitHub write access here.

**Comment by zeromus** [comment]
You have whatever permissions you need. You havent accepted the invite yet. I have no objections. Accept the invite and merge it yourself. Or don't, and in a few days I will get tired of seeing this here and merge it myself

**Comment by SineSwiper** [comment]
My bad.  I found it.  Thanks.

**Pull request merged**
