### PR TITLE
Add LCD Mod Compatible Zapper support

### PR DESCRIPTION
**Pull request by JasonWThompson**
Adds a two button controller that can be used to represent the states of a real Zapper. This requires hardware to translate a physical NES Zapper (or 3rd party equivalent) into said two button USB gamepad. One button represents the light sensor. The other represents the trigger.

To configure the light sensor, the player clicks on the light sensor configuration button and then waves the Zapper in front of a light that the Zapper can see. To configure the trigger, the player can simply press the trigger and then release it.

This setup has been tested and proven using the modified version of Duck Hunt from http://neslcdmod.com/

### CODE REVIEW

**Comment by JasonWThompson** [comment]
Dang it... I'll have to tackle getting it to build under Ubuntu later. I'll just hope that if it works in Ubuntu, it'd also work in OSX as I don't have access to OSX test that on.

**Comment by bbbradsmith** [comment]
https://github.com/TASVideos/fceux/blob/ca472ee6aed57821e3a0f75eb34a5e120e8ad3f5/src/git.h#L61

I think this should be called something else besides "Real Zapper". That name will cause too much confusion, as the existing "Zapper" is what almost all users would want to use and "Real" doesn't do anything to make it clear that it's not what they want.

Not sure what to suggest, but "Manual Zapper" or "Debug Zapper" are two ideas that come to mind.

(The in-code name being RealZapper is fine. I don't care about the part that isn't user-facing.)


Additionally the Linux/MacOS builds are failing with "undefined reference to FCEU_InitRealZapper(int)". I think there's a place for that stuff somewhere in the SDL version code, but I don't remember offhand where it goes.

**Comment by mjbudd77** [comment]
It just looks to me like the new file In the core source input area was not added to the src/CMakeList.txt. if this is done, the Linux/mac os builds will at least try to compile it. As long as that file follows cross platform rules, it should build.

**Comment by JasonWThompson** [comment]
I agree @bbbradsmith regarding the naming. "Real Zapper" is confusing to someone who just wants to play video games. I don't like "Manual Zapper" or "Debug Zapper" either because neither reflect the purpose of this. What makes this confusing is that the current dropdown list reflects "What is being emulated?" and not "How is this being emulated?". For both the mouse based Zapper emulation and the light gun based Zapper emulation, the answer that follows convention is "Zapper".

I'm going to let this sit for awhile while I work on getting me some more free time to make a further enhancement. I think the UX friendly solution is to remove the "Real Zapper" from the drop down and make the "Zapper" option configurable. In its configuration dialog, it could have some sort of toggle between "mouse" (the default) and "gamepad". This could drive what driver is used in the emulator.

If I find that to be too difficult (I'm not a C++ developer), I might call it "Hardware Zapper (advance)" and call it a day. 😅

**Comment by bbbradsmith** [comment]
The reason I suggest not making it a configuration of the existing zapper is that doing both in one would drastically overcomplicate the individual code. The concept is completely and fundamentally a different kind of device for the emulator, they are not two modes of the same thing. One is a mouse interface that simulates the entire timing chain and video signal interaction of the zapper, the other is none of that. I don't think it's useful to try to merge them for the user's benefit either.

Like I said in #130 this kind of input interface for the emulator is not suitable for getting a meaningful response out of any existing zapper game, with or without the USB zapper you're proposing. This at best is only going to work with newly made NES software that can tolerate lag and very coarse light sensor timing.

At face value what it's doing right now is literally letting you press buttons to "manually" adjust the zapper signal, which is why I suggested that name. The "debug" suggestion was because debugging new zapper software seems to be the most plausible use someone would have for it. Yes, I understand you're building a USB hardware interface for a zapper, so you want to call it "Hardware Zapper", but in this case we're talking about a one-off peripheral that only you have (if you have yet built it). There is no known thing called "Hardware Zapper" right now. Maybe "Experimental Hardware Zapper" would adequately describe this?


Ultimately though my qualms about the name are part of the question of who this feature is for. Is this a thing you really want to see in the master branch of FCEUX? For the purposes of your experiment, you have what you need from your own fork. If this feature requires a DIY hardware project to be useful to anybody, I think it would best be kept as its own forked version of the software? A benefit of this for you is that you could make other more intrusive changes that could better support the hardware project.

I was trying to look at this from the standpoint of maybe being useful as a generic debugging feature, but maybe even that is a little dubious... another idea might be to call it "Raw Input" and make 5 buttons, one for each of the data lines, rather than just the 2 that zappers used. Your hardware project could make use of that more complete interface just as well as one with only 2 data lines, I think, but it would support more or less any interface ideas of that shape... presuming they're useful with the low rate of polling FCEUX is capable of (i.e. once per frame).

(One thing that I notice immediately while testing it is that since the NES zapper gives a 0 bit for light-sensed, right now pressing a button means "light not sensed" and leaving a button open means "light sensed"... which does make sense for a raw input idea, but doesn't seem like what I'd expect from a human interface...)

**Comment by JasonWThompson** [comment]
I'm going to call it "LCD Mod Compatible Zapper". It's purpose is to allow people to play the modded NES games from http://neslcdmod.com/. 

Whether or not this feature is appropriate for this emulator isn't for me to decide. Worst case scenario, it just sits on my fork.

Regardless of where this goes I appreciate your guidance from both the responses from my issue request and your YouTube video that pointed me to the right resources.

**Comment by JasonWThompson** [comment]
Made the appropriate changes. 

I want to address a few of comments you made, @bbbradsmith 

> in this case we're talking about a one-off peripheral that only you have (if you have yet built it)

First check out this unlisted video I uploaded, it should have all the answers you need. 🙂
https://www.youtube.com/watch?v=ROai3Ov7Cts

Second, I don't think this is a one off. I picked using a joypad as input on purpose so that anyone could do this with whatever peripheral they choose to use. They just have to get the PC to read it as a joypad. Now for my _exact_ USB adapter. It is a very easy project that just about anyone can throw together in about an hour. I will eventually be documenting exactly how to do that.

> who this feature is for

Anyone who wants a more pure experience playing Duck Hunt. Using a mouse fundamentally changes the game into something else entirely. I don't disagree that there are some people who just want to click on ducks. But there are others out there who want to actually experience the game as it was intended to be experienced.

>  If this feature requires a DIY hardware project to be useful to anybody, I think it would best be kept as its own forked version of the software?

I think if it was in the master branch there would be people who will use it. It's more like the XBox adaptive controller than an XBox controller. The XBox adaptive controller provides a means of providing inputs that get translated to XBox rather than provide a full controller implementation. Likewise, this provides a means of providing inputs that get used by the emulator in a way that is otherwise impossible.

All that being said, if ultimately it is decided that this is inappropriate for this project then I'm cool with that. 🙂

**Comment by bbbradsmith** [comment]
That's really cool! If it's not hard to build I'll definitely want to make one for myself.

I'm not sure what you mean by "whatever peripheral", though. The clear intent is for a light sensor specifically, is it not? What other peripheral do you have in mind that could do something meaningful here?

Though as an aside, re: making the mouse input more like the original thing, I've seen a few different people use a Wiimote as a mouse, which I think is actually fairly easy to get working via some bluetooth software. Not the same technology as the original zapper of course, but it is a way that you can make the mouse input interface feel a lot more like it (and works with old game software).

Anyway, I'm not opposed to it moving into the main branch, but it seems like an unprecedented situation where it is designed for a hardware device that I think you're the first person to ever build.

The other suggestion I made was to make the interface for all 5 data lines connected to $4016 rather than just the 2 used by the zapper, and then it could be a generic low-rate input interface, for which I have no specific purpose in mind, but it'd be a more complete superset of what you've already done. The reason I said that might be dubious is because I think every other custom input device idea I've seen for the NES used serial input, rather than something that could deliver all its input in a single read of $4016. Even the zapper was originally meant to be polled rapidly through the frame... so the LCD Mod project might be the singular example of this kind of thing at this point?

**Comment by JasonWThompson** [comment]
I'm going to contradict myself within this response. 😅 I don't think being able to read all of the pins is a silly idea. In fact, take a look at my adapter in the picture below.

image

That red wire goes to D1 (I've been calling the 3 inputs D1, D2, and D3 though I've seen different sites call it different things). So it certainly is possible. The reason I didn't do it is because I struggled to see if it was _as meaningful_. With the zapper one can throw the latch pin (the black wire in my pic) HIGH and then LOW and then read both D2 and D3. No need to even pulse! Here's the source code of the function that does the reading:

```
// From my USB adapter, not FCEUX
dataForController_t getControllerData(void){
  // Latch. This tells the controller to get ready to send input.
  digitalWrite(LATCH, HIGH);
  delayMicroseconds(12);
  digitalWrite(LATCH, LOW);

  dataForController_t controllerData = getBlankDataForController();
  controllerData.crossOn = !digitalRead(D2);
  controllerData.circleOn = !digitalRead(D3);

  return controllerData;
}
```

With a normal controller however, one has to toggle the pulse each time to provide data. So if I represent D1 as a button, I would have to somehow have the emulator send the pulse bit to the USB adapter (perhaps using a rumble feature?). In any case, I felt like perhaps I was going off steering away from anything that was meaningfully useful. 

If it feels like I'm rambling, I agree. Which is why I didn't do it. 😅 I stopped and said, I want the buttons to represent functions and not pins.

Alright. So what are my plans? Next I'd like to expand this out to emulate the NES Vs. Zapper. Unfortunately my local arcade is closed due to COVID, so I don't have a means of seeing a real one up close. But my understanding of the spec is that it functions mostly the same but also has some control input coming in from D1. Thus whatever additional buttons the Arcade Zapper has I'll represent as buttons and work out the peculiarities of what happens in $4016 and $4017 within the emulator itself.

Also I'm going to port this to the retroarch version of FCE* because I have to see if the original gun can work on a CRT using the emulator. 🙂

image

**Comment by bbbradsmith** [comment]
Hmm, well the convention I'm used to is D(n) refers to data line/bit n of a $4016/4017 read. There are each 5 lines physically connected to the NES CPU (through an inverter).

3 of those lines are connected to the NES [controller port](https://wiki.nesdev.com/w/index.php/Controller_port_pinout) (D0, D3, D4) and 2 more are connected to the [expansion port](https://wiki.nesdev.com/w/index.php/Expansion_port). The expansion port wasn't really used for the NES, but on the Famicom there are peripherals that use D1 and D2.

The other 3 bits of $4016 aren't connected to anything and exhibit kinda weird ["open bus" behaviour](https://wiki.nesdev.com/w/index.php/Controller_reading#Unconnected_data_lines_and_open_bus), which can vary depending on what's in the cartridge or whether it's a clone system etc.

So I guess if you're seeing it labelled as "D1, D2, D3" in some places, that's just numbering the wires from the controller? I dunno, but when I say D0-D4 I'm referring to the lines of $4016.

.

So what I meant about a 5 lines generic interface is that it would just be assigning 5 buttons to the 5 data lines. The latch and clock lines would not be part of this (well, they're both output signals, not input). Whenever the emulator gets a $4016/4017 read it would give these 5 bits. This would not be for interfacing with standard controllers, which require repeated reads for serial input, but for any theoretical thing that only needs a single on/off state for this.

The zapper vs. LCD Mod ROMs is the only thing that fits that description. I don't have any proposed uses for the other bits, but it just seems like this might as well include them, since they're there, rather than make it only for zapper. ...but on the other hand I don't know if anybody would ever use them.

.

The Vs. Zapper on the other hand, if you want to interface with that, this can already be accommodated by the existing "Gamepad" interface device, with the buttons assigned correctly. That should be doable without any modifications to FCEUX, but you'd need LCD Mod style patches for the Vs. games.

If you just want to use the Vs. Zapper hardware and not the Vs. zapper game software, you could convert its serial report to the format used by the regular zapper and play the existing LCD Mod software?

**Comment by JasonWThompson** [comment]
Thank you for that resource! I can now see why I was so confused about 5 pins. 😄 In researching this project I found a bunch of different documents calling the pins a bunch of different things. I'll use the nomenclature from that document from now on when talking about pins. 😅 And, I'll update my adapter code to use that as constants so I can be consistent with the NESDev wiki. As you can probably tell, before touching this project I had never done anything with the NES before.

I now have a much better understanding of what you're talking about. I can add the other buttons. For the sake of making it easy, I might do something like this for the options:

```
+------------+
|     D0     | : 
+------------+
+------------+
|     D1     |
+------------+
+------------+
|     D2     |
+------------+
+------------+
|     D3     | : (eg - Zapper photo sensor)
+------------+
+------------+
|     D4     | : (eg - Zapper trigger)
+------------+

```

In addition, I'll change this to "Custom Controller (Advance)"

**Comment by bbbradsmith** [comment]
"LCD Compatible Zapper" is maybe a good name for it still? Even with the extra bits exposed, since that's the only proposed use at the moment anyway.

I don't have any useful labels for D0-D2 here. D0 is the one most commonly used by controllers, but only serially. I don't think there's any existing peripheral/game that would make use of this non-serial interface for any of those 3 lines.

**Comment by ClusterM** [comment]
Any progress on this? I planned to made same mod too. It's really interesting to connect real zapper to PC.

**Comment by r57zone** [comment]
It would be great if appeared was also a comport read capability so that could do the same using a simple Arduino.

**Comment by r57zone** [comment]
It turned out that can connect a [light gun via Digispark](https://github.com/r57zone/Zapper-Light-Gun-PC). Maybe it will be useful to someone who stumbles upon this.

**Comment by Boojakascha** [comment]
I can contribute to the discussion of whether or not it works with non patched ROMs. It does :P 
Here in this video you can see for yourself
https://youtu.be/zikiFYUYBj0?t=313

**Pull request merged**
