### PR TITLE
Customizing Hex Editor and Debugger Highlight Colors

### PR DESCRIPTION
**Pull request by owomomo**
As the title describes, colors of Hex Editor and Debugger text can be customized now.

### CODE REVIEW

**Comment by vadosnaprimer** [comment]
You keep adding changes. When will this be considered complete?

**Comment by owomomo** [comment]
Now it's fully functional and can be merged to the master branch. I'll not commit to this branch for a long time unless I find severe bugs.
I only want to make the colors of Hex Editor color configurable at first, but then my idea keeps coming out and can't stop myself... sorry.

**Comment by vadosnaprimer** [comment]
It looks like the colors button for debugger is too wide, so Default window size doesn't get rid of scrollbars in disassembly view. Either adjust the button width or window size that it treats as default (note that it has to be adjusted for IDA font too).

Also is it possible to show current color in hexadecimal in the menu command that sets a color? Like "PC\t0x0000FF".

**Comment by owomomo** [comment]
My opinion is adding a color square icon in the head of each menu item to directly see what color it is, but the actural color code is also on the right side of the menu.

**Comment by vadosnaprimer** [comment]
I think it's easier to tell which color it is by looking at exact numbers, once you're familiar with RGB represented as 24 bits. Because hexadecimal tells you immediately how much of each color is there, while it may be hard to distinguish colors if they're shown in tiny boxes. And I think text is easier to implement.

**Comment by owomomo** [comment]
This feature finally completed with menu shows both actual color icon and hex color code in each item.
Maybe there are further optimization can be done, but I'll not make too much changes so long as it currently works fine.

**Comment by vadosnaprimer** [comment]
Looks nice! Please add a space after the color icon so it separated from the menu text.

**Comment by owomomo** [comment]
> Looks nice! Please add a space after the color icon so it's separated from the menu text.

Are you using Windows XP? It looks fine on Windows 7 and 10, I tested it on Windows XP and found your problem.

**Comment by owomomo** [comment]
I currently don't have more stuff to commit to this pull request. If anyone encountered bugs, please comment here.

**Comment by vadosnaprimer** [comment]
`Default window size` now sets wrong size. There should be no vertical scrollbar for disasm. And it should be different (wider) when `IDA font` is enabled.

**Comment by owomomo** [comment]
> `Default window size` now sets wrong size. There should be no vertical scrollbar for disasm. And it should be different (wider) when `IDA font` is enabled.

Do you mean "horizontal scrollbar"? The vertical scroll bar for disassembly view is a static control that can't automatically hide, but I realized that a horizontal scrollbar is shown after selecting IDA font. If I misunderstood, could you explain it further or provide a picture for me.

**Comment by vadosnaprimer** [comment]
Hard-reset your master branch to some commit that's before 2ed70cf1b0e21f8678a67b8b86bed158e1365492, then pull from upstream master.

**Pull request merged**
