### PR TITLE
Refactored input system for Windows version

### PR DESCRIPTION
**Pull request by ClusterM**
### Main target: [Feature Request] Add the ability to bind load and save state to gamepad #312

The problem: FCEUX has multiple different routines to bind keys and check for keypresses.

`DWaitButton()` / "DWBDIALOG":
* **Allows binding of joystick buttons and axes**
* Allows binding of multiple buttons to one function
* Uses `ButtConfig` structure to store buttons config
* Uses `DTestButton()` function to check if key/button is pressed
* Uses `MakeButtString()` function to make human-readable string from `ButtConfig` which uses WinAPI call

`AskForHotkey()` / "NEWINPUT":
* Allows binding of key combinations (like Ctrl+R, etc.)
* Stores bindings as simple int value, array `int FCEUD_CommandMapping[]` used to store hotkeys
* Uses `FCEUD_TestCommandState()` function to check if key is pressed
* Uses `GetKeyComboName()` function to make human-readable string from binding which uses hardcoded table of strings

What have I done:
* `DWaitButton()` allows to bind joystick buttons, multiple buttons as well as key combinations
* `ButtConfig` modified to store meta key flags, e.g. key combinations with Ctrl, Alt, Shift
* `DTestButton()` can test key combinations
* `MakeButtString()` takes key combinations into account
* `int FCEUD_CommandMapping` replaced with `ButtConfig FCEUD_CommandMapping`
* `AskForHotkey()` calls replaced with `DWaitButton()` 
* `GetKeyComboName()` calls replaced with `MakeButtString()`
* All `FCEUD_CommandMapping` related code updated to use `ButtConfig` structure, including `FCEUD_TestCommandState()`
* Removed unused code
* Related config keys updated to keep compatibility with config files of previous versions

So it's possible to bind joystick buttons to hotkeys, finally.

image

image

Bonus:
* Support for Z, Rx, Ry, Rz axes (required by modern gamepads for second stick and trigger buttons)
* Support for key combinations with "Win" keys
* "Cancel" button into `AskForHotkey()` / "NEWINPUT" dialog to revert binding config
* Code clean-up

### CODE REVIEW

**Comment by zeromus** [comment]
Uhhh I dunno, man. Does it work? We can merge this as long as @ClusterM commits to sticking around for several months to clean up any possible problems.

**Comment by ClusterM** [comment]
I promise to clean up problems, I'm working with fceux every day.

**Comment by zeromus** [comment]
OK, good. is the PR ready to go?

**Comment by ClusterM** [comment]
Seems like it :)

**Pull request merged**
