### PR TITLE
Add to ram watch 3 bytes data size option.

### PR DESCRIPTION
**Pull request by schdub**
Implementing feature request #299.

### CODE REVIEW

**Comment by mjbudd77** [comment]
This all looks good except I don't think the signed representation of the 3 byte value will be correct because of how sign bit of the 3 byte value being is mapped into the int32_t. Since there is no primitive integer type in C++ that is 3 bytes, some special code needs to be written to handle the signed conversion. That said, I think that the unsigned values will work just fine, so I'm still inclined to merge it unless you want to fix it further.

**Comment by mjbudd77** [comment]
I think with some minor modifications we could have made your implementation work. I hope you aren’t giving up on this, you were really close

**Comment by schdub** [comment]
@mjbudd77 thanks. I'm still working on this feature.

What you thinking about this changes?
https://github.com/TASVideos/fceux/commit/82c1d651d1f25c6ec67bff0ee479dbcf2012ce84

**Comment by mjbudd77** [comment]
I made some comments on the commit you referenced. Keep in mind how negative numbers are represented in binary as 2's complement
```-1 = 0xFF
   -2 = 0xFE
   -3 = 0xFD
   .....  = ......
   -126 = 0x82
   -127 = 0x81
   -128 = 0x80
```
I suggest writing some small functions to do the conversions from 32 bit to 24 bit and back.

**Pull request closed without merging**
