### PR TITLE
New features in Symbolic Name Debugging

### PR DESCRIPTION
**Pull request by owomomo**
I think this is the last feture which can be updated before public release of 2.3.0

### CODE REVIEW

**Comment by mjbudd77** [comment]
How extensive are these changes? Should I also make them to the SDL port? Before this modification I had the SDL port matching the windows port capabilities

**Comment by owomomo** [comment]
> How extensive are these changes? Should I also make them to the SDL port? Before this modification I had the SDL port matching the windows port capabilities

I didn't do anything to the internal format of the .nl file, all the improvements are on the UI. The features which could only be done by editing the .nl file itself, such as multiline comment, array comments etc can directly be done in the debugger now.

**Comment by vadosnaprimer** [comment]
I don't understand what the array feature does.

**Comment by owomomo** [comment]
> I don't understand what the array feature does.

It's similar to one of the format in nl file: [http://fceux.com/web/help/NLFilesFormat.html](url), for example, when you name $C000 with "SomeText" and select the array with size of 0xF, then $C000 is named "SomeText[0]", $C002 is named "SomeText[2]", $C006 is named "SomeText[6]"... and so on.
The last address which have the name is $C000E, it is named "SomeText[E]".

**Comment by mjbudd77** [comment]
After adding an array, is it intended that if you try edit an element that it is treated as a individual symbol?

**Comment by owomomo** [comment]
> After adding an array, is it intended that if you try edit an element that it is treated as a individual symbol?

Yes, every symbol in the array is individual. If one of them are edited, the others don't change.

**Comment by mjbudd77** [comment]
So really the array options only really apply if adding not editing

**Comment by owomomo** [comment]
> So really the array options only really apply if adding not editing. It is more of a convenient add of an array, but if you need to edit, you have to edit each individually

If you want to change all the symbols of the array, you should edit the name of the first element of the array, select the array size and select overwrite existing names of the addresses in array body.

**Comment by mjbudd77** [comment]
Ah ok, I understand the overwrite idea. I think I know how to modify the SDL port

**Comment by mjbudd77** [comment]
One more question, what is the init entry box for? Is that what the array index starts at?

**Comment by owomomo** [comment]
> One more question, what is the init entry box for? Is that what the array index starts at?

It's the start index number of the array. Using the $C000 example above, if the init value is set to 4, $C000 would be named "SomeText[4]" and $C002 is "SomeText[6]".

**Comment by vadosnaprimer** [comment]
Seems to work, but it needs an explanation in the help file (see readme).
https://github.com/TASVideos/fceux/tree/master/vc/Help

**Pull request merged**
