### PR TITLE
Fix Linux build errors

### PR DESCRIPTION
**Pull request by chrisbroome**
Enable usage of `nullptr` by passing `-std=c++0x`
- SConstruct
- src/Makefile.am

Add missing mappers to boards/Makefile.am.inc:
- boards/190.cpp
- boards/80013-B.cpp
- boards/hp10xx_hp20xx.cpp

### CODE REVIEW

**Comment by bbbradsmith** [comment]
Normally wary about changing compiler language requirements like that, but I suppose now that the minimum Visual Studio version is 2010 c++0x is implied by that, so this seems okay to me.

Though, the only cited need for this is nullptr, which is used exactly once in the code, so my gut reaction would usually be to replace nullptr rather than take on a new language spec, but like I said we're already there on Windows anyway. I suppose pull request #9 should use nullptr as well?

I plan to merge this, but I want to leave this open for a few more days in case there are any objections.

**Comment by chrisbroome** [comment]
@bbbradsmith I understand not wanting to up the compiler version. I changed `nullptr` to `NULL` on another branch and that compiled fine (with my other changes). If you want, I can make that change and take out the `-std=c++0x` changes.

**Comment by bbbradsmith** [comment]
Oh, I thought it was fine. I just meant I wanted to leave it open for comment for a few days in case anyone else thought it wasn't. (...though maybe committing it would be a better way to find out if anyone cares about the compiler change.)

**Comment by bbbradsmith** [comment]
Merged.

**Pull request merged**
