### PR TITLE
New icon for Windows version

### PR DESCRIPTION
**Pull request by ClusterM**
Check issue #362 for discussion and preview screenshots.

### CODE REVIEW

**Comment by ClusterM** [comment]
Do not merge until the author's permission granted.

**Comment by g0me3** [comment]
as for me, the icon designs with a text is a bit outdated for now ;) all the utilites icons have its name underneath, why you should put it on the icon as well? need tema lebedev here for sure.

**Comment by vadosnaprimer** [comment]
tema lebedev asked me to tell you that he agrees with @g0me3

**Comment by mjbudd77** [comment]
I think it looks good. Is this ready to merge?

**Pull request merged**
