### PR TITLE
Numerical Video Pixel Scaling Feature Added to Qt GUI Video Config Window

### PR DESCRIPTION
**Pull request by mjbudd77**

### CODE REVIEW

**Comment by shentino** [comment]
Kudos for this!

This way we get the best of both worlds on top of the centering bit.

**Comment by shentino** [comment]
Hey should I report here or as a bug/issue if stretching the window causes it to fail to honor the numerical zoom settings?  I just tested it

**Comment by mjbudd77** [comment]
The numerical zoom settings are a one time set when you hit the apply button on the video config page. From then on, if you drag the window corner it will still auto scale.

**Comment by shentino** [comment]
Is there a way to disable autoscale on window resize?  What I'd like to do is maximize the window but keep the fixed zoomed rendering area in the middle of the window with black padding.

**Pull request merged**
