### PR TITLE
UI improvements and detail fixes

### PR DESCRIPTION
**Pull request by owomomo**
1. Fix Map Hotkey dialog list header and add sort icon to the header of Map Hotkeys.
2. Fix Nametable Viwer checkbox state mismatch when closing and opening again.
3. Fix linux build error.
4. Ram search show cheat count in current range.
5. Detail Fixes.

### CODE REVIEW

**Comment by zeromus** [comment]
What are you actually doing? Are you fixing all the little things that annoyed you while working on a project?

**Comment by owomomo** [comment]
I have a little obsessive about the details of the UI. If I annoyed the master branch of the code too much, I apologize for that and cancel the merge request.

**Comment by zeromus** [comment]
Will you stick around to fix any bugs related to this commit?

**Comment by owomomo** [comment]
> Will you stick around to fix any bugs related to this commit?

I'll keep fixing the bugs caused by my commit as long as I can access github. But I would not do too much huge changes like this commit in after days.

**Pull request merged**
