### PR TITLE
Linux GTK GUI feature update

### PR DESCRIPTION
**Pull request by mjbudd77**
Build fixes for RHEL8 systems. Full upgrade to GTK3, all GTK2 deprecated widgets replaced. Linux SDL/GTK GUI now has cheat and RAM watch tool windows (Issue #112). Modified linux GTK display logic to always center image in window (Issue #99) . Bug fixes for GUI hot key window (Issue #69). Bug fix for --loadlua command line option when relative paths are given to script file (Issue #97). Various gcc compiler warning and cppcheck static code analysis warning cleanup. Added an appveyor pipeline config file that will perform a test build on both windows and linux (ubuntu 20.04LTS) platforms. Added memory view hex editor window for SDL/GTK3 GUI. Hex editor lacks color due to gtk3 textview color performance issues.

…tion is failing so I resorted to a simpler pkg-config check. Fixed lua library check, include path and linker flag references.

### CODE REVIEW

**Comment by zeromus** [comment]
Are you going to continue to maintain this or is it one-and-done

**Comment by mjbudd77** [comment]
I will maintain. My plan is to bring the Linux port up to date with the
existing windows functionality as much as possible. I am doing this on my
own time so I only ask for time to work through any issues that arise. In
addition to my previous comments, I now also have the debugger window
mostly functional and plan to start the cdlogger after that. Also, I would
appreciate any feedback anyone is willing to give on my work so that I can
better help contribute in a way that is best for the project.
Regards,
-mb

**Comment by zeromus** [comment]
You're unlikely to get any feedback since there's no reason for anyone to use fceux to debug except because they're used to using it already, and nobody on linux is used to using it because the debugging tools have never been on linux. So it's really weird for you to want to improve them. That said, if you want to take it over, be my guest, as long as you don't break anything. But if you're going to be maintaining this for the long haul, join us on irc on #fceu on freenode so you can get on the same wavelength.

**Comment by vadosnaprimer** [comment]
Also it's usually a bad idea to pull-request your entire fork all at once, infinitely adding more and more commits. It's impossible to check/verify/review/test all of it at once, or thing by thing. On the other hand, sending PRs feature by feature may not get enough attention either, because the project is dead.

It's good if you are dedicated, but imagine what happens if this is merged and you suddenly disappear. Doing this work in a branch (as a new member) would be good, and then you'd ask people who care about fceux (nesdev maybe?) to test build of your new branch, both on linux and windows. And only if it does work well, it can be merged to master.

Alternatively, we might release whatever we currently have, and then let you in completely?

**Comment by mjbudd77** [comment]
I have no problem moving my pull request to a different branch. I will say
that the Linux gui interface was in some definite need of attention.  In
addition to the new features I have added, I have also made numerous bug
fixes and deprecated widget replacements in the gtk based gui which I
believe will allow for the Linux port to live on for quite a while longer.
I certainly don't want the Linux support to be dropped and this is the main
reason I started contributing. Coding the extra features has just evolved
into a hobby for me as I have been on lockdown with my family for the last
couple of months. It sounds like you are unsure of how my changes should be
introduced into the main project. I want the community to benefit from my
efforts so let me know how you prefer I proceed.
Regards,
-MB

**Comment by zeromus** [comment]
Please proceed by joining us on irc on #fceu on freenode so you can get on the same wavelength.

**Comment by mjbudd77** [comment]
Closing this pull request to make new one that uses the new branch as its target destination.

**Pull request closed without merging**
